Packer base
Otus-DevOps-22-08/Alexander-High_infra pull request #4
Opened 2023-01-17 22:22 UTC by Alexander-High

# Выполнено ДЗ №5

 - [X] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Созданы файлы ubuntu16.json immutable.json и variables.json
 - В файле variables.json прописаны оснвые переменные билдера.
 - В файле immutable.json происходит вызов виртуальной магины YC, после чего на нее устанавливаются mongodb, ruby и приложение. И из этого создется образ.

## Как запустить проект:
 - Запуск на исполнение производится консольной командой:
packer build -var-file=variables.json immutable.json

## Как проверить работоспособность:
 - В результате выполнения всех действий в папке "Образы" появится образ с именнем  reddit-base-@timestamp
--

<br class="Apple-interchange-newline">
 
## PR checklist
 - [X] Выставил label с номером домашнего задания
 - [X] Выставил label с темой домашнего задания

2023-01-19 08:51 UTC, mrgreyves requested changes
Здравствуйте!)
Забыли добавить файл с переменными, нужно добавить фейковые переменные
Так же нужно добавить фейковый ключик
Выглядит как приключение на 20 минут
ДЗ отправляю на доработку =)

2023-01-28 14:20 UTC, mrgreyves requested changes
Здравствуйте!)
Я писал вам про добавление фейкового ключа
Просто добавьте его и укажите до него путь =)

2023-01-28 16:22 UTC, Alexander-High commented
Да вот с путем то как раз и были проблемы....

2023-01-29 15:12 UTC, mrgreyves approved these changes
Здравствуйте!)
Кажется что сейчас все хорошо и проблем нет =)

2023-01-30 19:17 UTC, merged